version: '3'

services:
  # Configuração do PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres            # Puxando do .env
      POSTGRES_PASSWORD: fg01032003        # Puxando do .env
      POSTGRES_DB: imoveis_financiamentos_db                  # Puxando do .env
    ports:
      - "5432:5432"                            # Porta padrão do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistência dos dados

  # Configuração da Aplicação Node.js
  app:
    build: .
    container_name: node_app_container
    environment:
      - DB_HOST=postgres                     # Puxando do .env
      - DB_PORT=5432                      # Puxando do .env
      - DB_USERNAME=postgres              # Puxando do .env
      - DB_PASSWORD=fg01032003              # Puxando do .env
      - DB_NAME=imoveis_financiamentos_db                      # Puxando do .env
    depends_on:
      - postgres                                # Certifica que o PostgreSQL está rodando antes da aplicação
    ports:
      - "3000:3000"                             # Porta da aplicação
    volumes:
      - .:/usr/src/app                          # Volume para desenvolvimento contínuo
    command: /bin/sh -c "npm run migrate && npm run start"

volumes:
  postgres_data:
