version: '3'

services:
  # Configuração do PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USERNAME}            # Puxando do .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}        # Puxando do .env
      POSTGRES_DB: ${DB_NAME}                  # Puxando do .env
    ports:
      - "5432:5432"                            # Porta padrão do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistência dos dados

  # Configuração da Aplicação Node.js
  app:
    build: .
    container_name: node_app_container
    environment:
      - DB_HOST=${DB_HOST}                      # Puxando do .env
      - DB_PORT=${DB_PORT}                      # Puxando do .env
      - DB_USERNAME=${DB_USERNAME}              # Puxando do .env
      - DB_PASSWORD=${DB_PASSWORD}              # Puxando do .env
      - DB_NAME=${DB_NAME}                      # Puxando do .env
    depends_on:
      - postgres                                # Certifica que o PostgreSQL está rodando antes da aplicação
    ports:
      - "3000:3000"                             # Porta da aplicação
    volumes:
      - .:/usr/src/app                          # Volume para desenvolvimento contínuo
    command: npm run start                      # Comando para rodar a aplicação

volumes:
  postgres_data:
