version: '3'

services:
  # Configuração do PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fg01032003
      POSTGRES_DB: imoveis_financiamentos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exban-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  # Configuração da Aplicação Node.js
  app:
    build: .
    container_name: node_app_container
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=fg01032003
      - DB_NAME=imoveis_financiamentos_db
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
    networks:
      - exban-network
    command: /bin/sh -c "npm run migrate && npm run start"

networks:
  exban-network:
    driver: bridge

volumes:
  postgres_data:
